### ISSUE TITLE
Lack of fonts breaks png output

### ISSUE THREAD

**Issue by ianmcorvidae** [markpfletcher/graphviz-docker#1]
Since there's not really any fonts installed, the text just ends up being a string of boxes. SVG output works since it doesn't require the in-container graphviz install to have access to fonts. I couldn't figure out exactly where the default fonts graphviz wants to use are in alpine linux, but you at least get _something_ with the addition of `font-bitstream-type1` (though it ends up monospace, which most typical installs wouldn't give you).

**Comment by otobrglez** [comment]
You need to install some fonts,.. something like this works for me.

```Dockerfile
RUN apk add --update --no-cache graphviz font-bitstream-type1
```

Cheers!

**Comment by maddiefletcher** [comment]
Thanks for posting - I've updated the image to include font-bitstream-type1 and ghostscript-fonts
